@extends($activeTemplate.'layouts.frontend')

@section('content')
<div class="pt-150 pb-150" style="background: var(--navy-dark); min-height: 100vh;">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-lg-8">
                <div class="section-header text-center">
                    <span style="color: var(--gold); font-size: 0.9rem; font-weight: 700; text-transform: uppercase; letter-spacing: 2px;">Multiple Revenue Streams</span>
                    <h2 class="mt-2 mb-3" style="color: #fff; font-size: 2.5rem;">4 Ways to Generate Wealth</h2>
                    <p style="color: var(--text-white); font-size: 1.1rem; opacity: 0.9;">Our algorithmic trading ecosystem provides four distinct pathways to accelerate your portfolio growth, combining active yields with powerful passive networking bonuses.</p>
                </div>
            </div>
        </div>

        <div class="row gy-4 justify-content-center">
            <!-- 1. Daily NFT Yield -->
            <div class="col-xl-3 col-lg-4 col-md-6 mb-30">
                <div class="custom--card h-100" style="padding: 40px 25px; border-top: 3px solid var(--teal); background: rgba(255,255,255,0.02); border-radius: 15px;">
                    <div style="width: 70px; height: 70px; background: rgba(45, 212, 191, 0.1); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 20px;">
                        <i class="las la-chart-line" style="font-size: 2.5rem; color: var(--teal);"></i>
                    </div>
                    <h4 class="text-center" style="color: #fff; margin-bottom: 15px;">Daily Bot Yield</h4>
                    <h3 class="text-center" style="color: var(--gold); margin-bottom: 15px;">~5% <span style="font-size: 1rem; color: #fff; opacity: 0.7;">/ Day</span></h3>
                    <p class="text-center" style="font-size: 0.9rem; opacity: 0.85; color: #fff;">Earn daily automated profits generated by our high-frequency arbitrage bot just by holding a platform NFT.</p>
                </div>
            </div>

            <!-- 2. Direct Referral Bonus -->
            <div class="col-xl-3 col-lg-4 col-md-6 mb-30">
                <div class="custom--card h-100" style="padding: 40px 25px; border-top: 3px solid var(--gold); background: rgba(255,255,255,0.02); border-radius: 15px;">
                    <div style="width: 70px; height: 70px; background: rgba(246, 224, 94, 0.1); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 20px;">
                        <i class="las la-users" style="font-size: 2.5rem; color: var(--gold);"></i>
                    </div>
                    <h4 class="text-center" style="color: #fff; margin-bottom: 15px;">Direct Referral</h4>
                    <h3 class="text-center" style="color: var(--gold); margin-bottom: 15px;">10% <span style="font-size: 1rem; color: #fff; opacity: 0.7;">Instant</span></h3>
                    <p class="text-center" style="font-size: 0.9rem; opacity: 0.85; color: #fff;">Receive a massive 10% instant commission deposited directly to your wallet every time someone joins using your referral link.</p>
                </div>
            </div>

            <!-- 3. Code Income (Indirect) -->
            <div class="col-xl-3 col-lg-4 col-md-6 mb-30">
                <div class="custom--card h-100" style="padding: 40px 25px; border-top: 3px solid #00d2ff; background: rgba(255,255,255,0.02); border-radius: 15px;">
                    <div style="width: 70px; height: 70px; background: rgba(0, 210, 255, 0.1); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 20px;">
                        <i class="las la-network-wired" style="font-size: 2.5rem; color: #00d2ff;"></i>
                    </div>
                    <h4 class="text-center" style="color: #fff; margin-bottom: 15px;">Code Income</h4>
                    <h3 class="text-center" style="color: #00d2ff; margin-bottom: 15px;">2% <span style="font-size: 1rem; color: #fff; opacity: 0.7;">Indirect</span></h3>
                    <p class="text-center" style="font-size: 0.9rem; opacity: 0.85; color: #fff;">The power of networking! Earn a 2% passive "Code Bonus" from the deposits of people brought in by your direct referrals.</p>
                </div>
            </div>

            <!-- 4. Self Deposit Bonus -->
            <div class="col-xl-3 col-lg-4 col-md-6 mb-30">
                <div class="custom--card h-100" style="padding: 40px 25px; border-top: 3px solid #ff5722; background: rgba(255,255,255,0.02); border-radius: 15px;">
                    <div style="width: 70px; height: 70px; background: rgba(255, 87, 34, 0.1); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 20px;">
                        <i class="las la-wallet" style="font-size: 2.5rem; color: #ff5722;"></i>
                    </div>
                    <h4 class="text-center" style="color: #fff; margin-bottom: 15px;">Self-Deposit Bonus</h4>
                    <h3 class="text-center" style="color: #ff5722; margin-bottom: 15px;">5% <span style="font-size: 1rem; color: #fff; opacity: 0.7;">Cashback</span></h3>
                    <p class="text-center" style="font-size: 0.9rem; opacity: 0.85; color: #fff;">Get an automatic 5% instant cashback bonus credited to your wallet immediately upon making your own personal deposit.</p>
                </div>
            </div>
        </div>
        
        <div class="text-center mt-5">
            <a href="{{ route('user.home') }}" class="btn btn-primary" style="padding: 12px 30px; font-weight: 600;">@lang('Go to Dashboard')</a>
        </div>
    </div>
</div>

<style>
    .custom--card { transition: transform 0.3s ease; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }
    .custom--card:hover { transform: translateY(-10px); background: rgba(255,255,255,0.05) !important; }
</style>
@endsection
